diplom/urls.py
from django.contrib import admin
from django.urls import path
from logistic import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view()),
    path('orders/', views.ReestrOrders.as_view(), name='orders'),
    path('<int:pk>/', views.ShowOrder.as_view(), name='show_order'),
    path('orders/create/', views.CreatOrder.as_view(), name='create_order'),
    path('client/<int:pk>/', views.ClientCard.as_view(), name='client'),
    path('client/<int:pk>/upload_balance/', views.CreateUserBalance.as_view(), name='upload'),
    path('client/<int:pk>/create_correspondance/', views.CreateCorrespondence.as_view(), name='create_correspondance'),
    path('correspond/', views.ShowCorrespondence.as_view(), name='show_correspond'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistic/models.py
from django.db import models


class Order(models.Model):
    """ Модель карточки заказа"""
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='order')
    city_auction = models.ForeignKey('CityAuction', on_delete=models.CASCADE, related_name='city')
    name_auction = models.CharField(max_length=250)
    address_auction = models.CharField(max_length=250)
    number_order = models.IntegerField()
    model_transport = models.CharField(max_length=250)
    description = models.TextField()
    place_delivery = models.ForeignKey('PlaceDelivery', on_delete=models.CASCADE, related_name='delivery')
    transportation = models.ForeignKey('Transportation', on_delete=models.CASCADE, related_name='transport')
    correspondence = models.TextField()
    service = models.ManyToManyField('Services')
    photo = models.ImageField(upload_to='image', default=None, null=True,  blank=False)
    price = models.FloatField(default=0)

    class Meta:
        db_table = 'order'
        ordering = ['id']

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    def calculated_price(self):
        """
        Функция для расчета цены

        """
        order_id = self.id
        services = Order.objects.get(id=self.id).service.all()
        print(order_id)
        count_service = 0
        # Расчет стоимости услуг
        for service in services:
            count_service += service.ser_price
            print(count_service)
        # Расчет стоимости услуг с учетом места отпрвки
        delivery = Order.objects.filter(id=self.id)
        for val in delivery:
            count_service += val.place_delivery.pd_price

        # Расчет стоимости услуг с учетом типа транспортировки
        transportation = Order.objects.filter(id=self.id)
        for val in transportation:
            count_service += val.transportation.tr_price

        return count_service

class Correspondence(models.Model):
    """Модель для хранения переписки в рамках заказа"""
    message = models.TextField()
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='correspond')
    order_id = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_core')

    class Meta:
        db_table = 'correspondence'


class BalanceOperation(models.Model):
    """Модель для хранения истории поплнения баланса"""

    user = models.ForeignKey('users.User', on_delete=models.CASCADE)
    sum = models.FloatField()
    date_operation = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'balanceoperation'






class CityAuction(models.Model):
    """Модель для хранения перечня городов с которыми работает система"""
    city_name = models.CharField(max_length=250)

    def __str__(self):
        return f'{self.city_name}'

    class Meta:
        db_table = 'cityauction'



class PlaceDelivery(models.Model):
    """Модель для хранения пунктов доставки до которых может быть доставлено ТС"""
    pd_name = models.CharField(max_length=250)
    pd_address = models.CharField(max_length=250)
    pd_price = models.FloatField()

    def __str__(self):
        return f'{self.pd_name}'
    class Meta:
        db_table = 'placedelivery'


class Transportation(models.Model):
    """Модель для хранения вариантов транспортировки"""
    tr_name = models.CharField(max_length=250)
    type_transport = models.CharField(max_length=250)
    tr_price = models.FloatField()

    def __str__(self):
        return f"{self.tr_name}"

    class Meta:
        db_table = 'transportation'


class Services(models.Model):
    """Модель для выбора дополнительных сервисов в закаyз"""
    ser_name = models.CharField(max_length=255)
    ser_price = models.FloatField()

    def __repr__(self):
        return f'{self.ser_name} , {self.ser_price}'

    def __str__(self):
        return f'{self.ser_name} - {self.ser_price}'

    class Meta:
        db_table = 'services'


class Auction(models.Model):
    name = models.CharField(max_length=250)
    def __str__(self):
        return f'{self.name}'
    class Meta:
        db_table = 'auction'

templates/base.html
<html>
<div class="container">


    <header>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Buy a car and we will deliver it</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/orders">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="create">Create order</a>

        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

    <header class="d-flex justify-content-center py-3">

        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4"></span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="" class="nav-link active" aria-current="page">Orders</a></li>
        <li class="nav-item"><a href="create" class="nav-link">Create order</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
    </header>
  </div>

<body>

    <div class="container">
        {% block content %}
        {% endblock content %}


    </div>
</body>

<footer class="footer mt-auto py-3 bg-body-tertiary"

>
  <div class="container" style="text-align: right;padding-right: 0px;margin-right: 20px;" >
    <span class="text-body-secondary">© Разработано в рамках диплома. Бакашев С.О </span>
  </div>
</footer>



</html>

templates/client.html
<!DOCTYPE html>
{% extends 'base.html' %} }}
{% block content %}
<html lang="en">

<body>
{% csrf_token %}
<div class="post-entry">
    <p>{{ user.balance }}</p>
    <p>{{ user.first_name }}</p>
    <p>{{ user.email }}</p>
     <p>{{ user.username }}</p>

</div>
    <a href="upload_balance" > Пополнить баланс </a>

</body>
</html>
{% endblock content %}

templates/create_correspondance.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}

    <!--Вставка -->

         <div class="container">

            <div class="py-5 text-center">

              <h2>Correspondence</h2>
              <p class="lead">Выможете оставить свой комментарий и мы обязатльно вам на него ответим.
                  Просьба соблюдать правила общения и не писать нецензурные вырожения</p>
            </div>

            <!-- отсюда убрал-->

              <div class="col-md-7 col-lg-8">

                <h4 class="mb-3">Комментарий</h4>

                  <div class="row g-3">
                  <form enctype="multipart/form-data" action="" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_message" class="form-label">Description</label>
                        <textarea class="form-control" id="id_message" rows="3" name="message"></textarea>
                    </div>
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Save</button>
                   </form>

                </div>
           </div>



                 </div>

    </div>






    <!-- End -->



{% endblock content %}

templates/create_order.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">

            <div class="py-5 text-center">

              <h2>Create your order</h2>
              <p class="lead">Заполнитете форму для создания фашего заказа. После заполнения всех полей, ваш заказ будет взят
                  в работу и свами свяжеться наш менеджер.</p>
            </div>

            <!-- отсюда убрал-->

              <div class="col-md-7 col-lg-8">

                <h4 class="mb-3">Информация о заказе</h4>

                  <div class="row g-3">
                  <form enctype="multipart/form-data" action="" method="post">
                    {% csrf_token %}
                    <div class="col-sm-6">
                      <label for="id_name_auction" class="form-label">Name auction</label>
                      <input type="text" class="form-control" id="id_name_auction" placeholder="" value="" required=""
                             name="name_auction">
                      <div class="invalid-feedback">
                        Valid first name is required.
                      </div>
                    </div>

                    <div class="col-sm-6">
                      <label for="id_address_auction" class="form-label">Address auction</label>
                      <input type="text" class="form-control" id="id_address_auction" placeholder="" value="" required=""
                      name="address_auction">
                      <div class="invalid-feedback">
                        Valid last name is required.
                      </div>
                    </div>

                    <div class="for-label">
                      <label for="id_number_order" class="form-label">Number order</label>

                        <input type="number" class="form-control" id="id_number_order" placeholder="" required=""
                        name="number_order">
                      <div class="invalid-feedback">
                          Your username is required.

                      </div>
                    </div>

                    <div class="col-sm-6">
                      <label for="id_model_transport" class="form-label">Model Transport</label>

                        <input type="text" class="form-control" id="id_model_transport" placeholder="" required=""
                        name="model_transport">
                      <div class="invalid-feedback">
                          Your username is required.

                      </div>
                    </div>



                    <div class="mb-3">
                        <label for="id_description" class="form-label">Description</label>
                        <textarea class="form-control" id="id_description" rows="3" name="description"></textarea>
                    </div>

                    <div class="col-12">
                      <label for="id_photo" class="form-label">Photo</label>
                        <input type="file" class="form-control" name="photo" accept="image/*" required="" id="id_photo">
                      <!--  <input type="file" class="form-control" id="photo" placeholder="" required="" name="photo">-->
                      <div class="invalid-feedback">
                          Your username is required.

                      </div>
                    </div>

                    <div class="col-12">
                      <label for="id_city_auction" class="form-label">City auction</label>
                      <select name="city_auction" class="form-select" required="" id="id_city_auction" >
                        <option  value selected>Choose...</option>
                          {% for city in city_act%}
                                <option value="{{ city.id }}">{{ city.city_name}}</option>
                          {% endfor %}
                      </select>
                      <div class="invalid-feedback">
                        Please select a valid country.
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="id_place_delivery" class="form-label">Place delivery</label>
                      <select name="place_delivery" class="form-select" required="" id="id_place_delivery" >
                        <option  value selected >Choose...</option>
                          {% for place in place_de%}
                                <option value="{{ place.id }}">{{ place.pd_name}}</option>
                          {% endfor %}
                      </select>
                      <div class="invalid-feedback">
                        Please select a valid country.
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="id_transportation" class="form-label">Transportation</label>
                      <select name="transportation" class="form-select" required="" id="id_transportation" >
                        <option  value selected >Choose...</option>
                          {% for transp in transports%}
                                <option value="{{ transp.id }}"> {{ transp.tr_name}}</option>
                          {% endfor %}
                      </select>
                      <div class="invalid-feedback">
                        Please select a valid country.
                      </div>
                    </div>


                    <div class="col-12">
                      <label for="id_service" class="form-label">Service</label>
                      <select name="service" class="form-select" required="" id="id_service" size="3" multiple>

                          {% for serv in services%}
                                <option value="{{ serv.id }}"> {{serv}}</option>
                          {% endfor %}
                      </select>
                      <div class="invalid-feedback">
                        Please select a valid country.
                      </div>
                    </div>
                    <button class="w-100 btn btn-primary btn-lg" type="submit">Create order</button>
                   </form>

                </div>
           </div>
    <!-- убрал акрытие form -->


                 </div>

    </div>



{% endblock content %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Стартовая страница</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</head>

<!doctype html>
<html lang="ru" data-bs-theme="auto">
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Пример на bootstrap 5: Форма входа - макет и дизайн формы · Версия v5.3.1">
	<title>Форма входа | Signin Template for Bootstrap · Версия v5.3.1</title>

	<link rel="canonical" href="https://bootstrap-5.ru/docs/5.3/examples/sign-in/">

	<!-- Bootstrap core CSS -->
<link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">


	<!-- Favicons -->
	<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
	<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
	<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
	<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
	<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
	<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
	<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="sign-in.css" rel="stylesheet">
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2017–2023</p>
  </form>
</main>

<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>


  </body>
</html>
</html>

templates/orders.html
{% extends 'base.html' %}


{% block content %}


    <article class="my-3" id="list-group">
      <div class="bd-heading sticky-xl-top align-self-start mt-5 mb-3 mt-xl-0 mb-xl-2">
        <h3>Перечень заказов</h3>

      </div>




        <div class="bd-example-snippet bd-code-snippet"><div class="bd-example m-0 border-0">
        <div class="list-group">
               {% for ord in object_list%}
        <a href={% url 'show_order' ord.id %} class="list-group-item ">{{ord.number_order}} | {{ ord.model_transport }}</a>




            {% endfor %}
        </div>

      </div>
        </div>
    </article>
    <div class=".flex-wrap">
        <div style="text-align: center">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">previous|</a>
        {% endif %}
        {% if page_obj.has_next %}

        <a href="?page={{ page_obj.next_page_number }}">next |</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last</a>


        {% endif %}
        </div>
    </div>
{% endblock content  %}

templates/show_correspondance.html
   {% block content %}

     {% for correspond in correspondence %}
         <div>
         <h5 class="mb-1">{{correspond.user}}</h5>
         <p class="mb-1">{{correspond.message}}</p>
        </div>

    {% endfor %}

{% endblock content %}

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/upload_balance.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Вставка-->
     <div class="container">

            <div class="py-5 text-center">

              <h2>Top up your balance</h2>
              <p class="lead">Введите сумму для пополнения баланса, при ввведении отрицательного значения баланс останется без изменения</p>
            </div>

            <!-- отсюда убрал-->

              <div class="col-md-7 col-lg-8">

                <h4 class="mb-3">Введите сумму для пополнения</h4>

                  <div class="row g-3">
                  <form enctype="multipart/form-data" action="" method="post">
                    {% csrf_token %}


                    <div class="for-label">
                      <label for="id_sum" class="form-label">Amount</label>

                        <input type="number" class="form-control" id="id_sum" placeholder="" required=""
                        name="sum">
                      <div class="invalid-feedback">
                          Your username is required.

                      </div>
                    </div>


                    <button class="w-100 btn btn-primary btn-lg" type="submit">Refresh</button>
                   </form>

                </div>
           </div>



                 </div>

    </div>


{% endblock content %}